name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        mode: [release, dev]
        go: ["1.23.3"]

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build deej (Windows)
        if: runner.os == 'Windows'
        run: pkg/deej/scripts/windows/build-${{ matrix.mode }}.bat
        shell: cmd
      - name: Archive Windows build
        if: runner.os == 'Windows' && matrix.mode == 'release'
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: deej-release.exe
